changelog:
  exclude:
    labels:
      - ignore-release
    authors:
      - octocat
  categories:
    - title: Major Changes
      labels:
        - major-change
    - title: Minor Changes
      labels:
        - minor-change
    - title: Other Changes
      labels:
        - "*"